[project]
name = "ocior-mvbah"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyzmq>=27.0.0",
    "reedsolo>=1.7.0",
]
